/**
 * Type definitions for AgentCFO
 */

export type DocumentType = 
  | "invoice"
  | "receipt"
  | "contract"
  | "letter"
  | "tax_document"
  | "insurance"
  | "other";

export type DocumentStatus = "uploading" | "processing" | "completed" | "failed";

export interface Document {
  id: number;
  user_id: number;
  filename: string;
  original_filename: string;
  display_name?: string; // Human-readable name generated by AI
  file_size: number;
  mime_type: string;
  document_type: DocumentType;
  status: DocumentStatus;
  extracted_text?: string;
  language?: string;
  num_pages?: number;
  created_at: string;
  updated_at: string;
  // Filing cabinet fields
  storage_year?: number;
  category?: string;
  ocr_pdf_path?: string;
  // Intelligence documentaire
  importance_score?: number;
  document_date?: string;
  deadline?: string;
  extracted_amount?: number;
  currency?: string;
  keywords?: string; // JSON string
  classification_confidence?: number;
  // Duplicate detection
  is_duplicate?: boolean;
  duplicate_of_id?: number;
  similarity_score?: number;
}

export interface DocumentStatistics {
  total_documents: number;
  documents_by_type: Record<string, number>;
  documents_with_deadline: number;
  overdue_documents: number;
  upcoming_deadlines: number;
  high_importance_documents: number;
  average_importance_score: number;
  total_amount_extracted: number;
}

export interface ChatMessage {
  id?: number;
  role: "user" | "assistant" | "system";
  content: string;
  created_at?: string;
}

export interface Conversation {
  id: number;
  agent_type: "accountant" | "legal";
  title?: string;
  created_at: string;
  updated_at: string;
  message_count: number;
}

export interface FilingCabinetYear {
  year: number;
  document_counts: Record<string, number>;
  total: number;
}

export interface FilingCabinetStats {
  years: FilingCabinetYear[];
  total_documents: number;
  total_years: number;
}

// Hierarchical filing cabinet types (Year > Category > Type)
export interface CategoryTypeCount {
  [documentType: string]: number; // e.g., { "invoice": 3, "letter": 1 }
}

export interface HierarchicalFilingCabinetYear {
  year: number;
  categories: Record<string, CategoryTypeCount>; // e.g., { "Impots": { "invoice": 3 } }
  total: number;
}

export interface HierarchicalFilingCabinetStats {
  years: HierarchicalFilingCabinetYear[];
  total_documents: number;
  total_years: number;
}

export interface CategoryStats {
  category: string;
  document_counts: Record<string, number>;
  total: number;
}

export interface DocumentSearchResult {
  document: Document;
  year: number;
  category: string;
  document_type: string;
}

